import type { Machine, Material, ObjectType, RoomType } from '../types';

export const SEED_MATERIALS: Material[] = [
  { id: 'mat_allzweck', name: 'Allzweckreiniger', kind: 'reinigungsmaterial', unit: 'Liter', costPerUnit: 2.5, active: true },
  { id: 'mat_sanitaer', name: 'Sanitärreiniger', kind: 'reinigungsmaterial', unit: 'Liter', costPerUnit: 3.2, active: true },
  { id: 'mat_glas', name: 'Glasreiniger', kind: 'reinigungsmaterial', unit: 'Liter', costPerUnit: 2.8, active: true },
  { id: 'mat_wischpflege', name: 'Wischpflege', kind: 'reinigungsmaterial', unit: 'Liter', costPerUnit: 3.5, active: true },
  { id: 'mat_desinfekt', name: 'Desinfektionsreiniger', kind: 'reinigungsmaterial', unit: 'Liter', costPerUnit: 4.8, active: true },
  { id: 'mat_mikrofaser', name: 'Mikrofasertücher', kind: 'reinigungsmaterial', unit: 'Stück', costPerUnit: 0.9, active: true },
  { id: 'mat_mopp', name: 'Moppbezüge', kind: 'reinigungsmaterial', unit: 'Stück', costPerUnit: 4.5, active: true },
  { id: 'mat_pads', name: 'Maschinenpads', kind: 'reinigungsmaterial', unit: 'Stück', costPerUnit: 6.9, active: true },
  { id: 'mat_muell60', name: 'Müllbeutel 60 l', kind: 'reinigungsmaterial', unit: 'Rolle (25 St.)', costPerUnit: 2.2, active: true },
  { id: 'mat_muell120', name: 'Müllbeutel 120 l', kind: 'reinigungsmaterial', unit: 'Rolle (25 St.)', costPerUnit: 3.1, active: true },
  { id: 'mat_wc_papier', name: 'Toilettenpapier', kind: 'verbrauchsmaterial', unit: 'Rolle', costPerUnit: 0.45, active: true, note: 'Standard: Gestellung durch Auftraggeber' },
  { id: 'mat_papierhand', name: 'Papierhandtücher', kind: 'verbrauchsmaterial', unit: 'Pack', costPerUnit: 2.8, active: true, note: 'Standard: Gestellung durch Auftraggeber' },
  { id: 'mat_seife', name: 'Seife', kind: 'verbrauchsmaterial', unit: 'Liter', costPerUnit: 3.9, active: true, note: 'Standard: Gestellung durch Auftraggeber' },
  { id: 'mat_handdesinfekt', name: 'Händedesinfektionsmittel', kind: 'verbrauchsmaterial', unit: 'Liter', costPerUnit: 6.5, active: true, note: 'Standard: Gestellung durch Auftraggeber' },
];

export const SEED_MACHINES: Machine[] = [
  { id: 'ma_einscheiben', name: 'Einscheibenmaschine 16″', hourlyRate: 4.5, purchasePrice: 1800, usefulLifeYears: 8, maintenancePerYear: 150, energyCostPerHour: 0.3, active: true },
  { id: 'ma_scheuersaug', name: 'Scheuersaugmaschine 50 cm', hourlyRate: 12, purchasePrice: 6500, usefulLifeYears: 7, maintenancePerYear: 400, energyCostPerHour: 0.5, active: true },
  { id: 'ma_nasssauger', name: 'Nass-/Trockensauger', hourlyRate: 2.5, purchasePrice: 600, usefulLifeYears: 6, maintenancePerYear: 60, energyCostPerHour: 0.25, active: true },
  { id: 'ma_teppich', name: 'Teppichreinigungsmaschine (Sprühextraktion)', hourlyRate: 6, purchasePrice: 2200, usefulLifeYears: 7, maintenancePerYear: 180, energyCostPerHour: 0.3, active: true },
  { id: 'ma_hochdruck', name: 'Hochdruckreiniger', hourlyRate: 5, purchasePrice: 1400, usefulLifeYears: 7, maintenancePerYear: 120, energyCostPerHour: 0.6, active: true },
  { id: 'ma_kehrmaschine', name: 'Kehrmaschine', hourlyRate: 8, purchasePrice: 3800, usefulLifeYears: 8, maintenancePerYear: 250, energyCostPerHour: 0.4, active: true },
  { id: 'ma_buehne', name: 'Hubarbeitsbühne (Miete)', hourlyRate: 35, note: 'Mietkosten je Einsatzstunde inkl. Nebenkosten', active: true },
  { id: 'ma_solar', name: 'Osmose-/Solarreinigungssystem', hourlyRate: 9, purchasePrice: 3200, usefulLifeYears: 6, maintenancePerYear: 200, active: true },
];

export const SEED_OBJECT_TYPES: ObjectType[] = [
  'Büro',
  'Verwaltungsgebäude',
  'Praxis',
  'Zahnarztpraxis',
  'Arztpraxis',
  'Physiotherapie',
  'Schule',
  'Kita',
  'Hotel',
  'Pflegeheim',
  'Fitnessstudio',
  'Autohaus',
  'Küchenstudio',
  'Verkaufsfläche',
  'Supermarkt',
  'Lager',
  'Logistikzentrum',
  'Produktionshalle',
  'Werkstatt',
  'Treppenhaus',
  'Privathaushalt',
  'Baustelle',
  'Neubau',
  'Sonstiges',
].map((name, i) => ({ id: `ot_${i + 1}`, name, system: true }));

export const SEED_ROOM_TYPES: RoomType[] = [
  'Büro',
  'Großraumbüro',
  'Besprechungsraum',
  'Empfang / Eingangsbereich',
  'Flur / Verkehrsfläche',
  'Treppenhaus',
  'WC / Sanitärraum',
  'Dusche / Umkleide',
  'Küche / Teeküche',
  'Sozialraum',
  'Lager',
  'Archiv',
  'Serverraum',
  'Ausstellung / Verkaufsfläche',
  'Behandlungsraum',
  'Wartezimmer',
  'Labor',
  'Werkstatt',
  'Produktionsfläche',
  'Aufzug',
  'Sonstiger Raum',
].map((name, i) => ({ id: `rt_${i + 1}`, name, system: true }));

export const SEED_FLOOR_TYPES = [
  'PVC',
  'Linoleum',
  'Fliesen',
  'Naturstein',
  'Feinsteinzeug',
  'Laminat',
  'Parkett',
  'Teppich',
  'Beton',
  'Epoxidharz',
  'Gummi',
  'Sonstiges',
];
